//! Contract tests for outbox-relay.
//!
//! This service is a pure conduit: it reads a stored envelope out of Postgres
//! and republishes it to NATS **unchanged**. Its contract obligation is
//! unusual and strict — whatever it emits must be byte-for-byte what the
//! gateway stored.
//!
//! So the central test here is not "does it round trip" but "does it round
//! trip *without altering anything*". A relay that helpfully re-stamped an id
//! or a timestamp would break idempotency downstream, because consumers dedupe
//! on exactly those values.

use messaging_core::{Envelope, OrderCommand, subjects};
use uuid::Uuid;

/// A row exactly as the gateway writes it into the `payload` JSONB column.
const STORED_ROW: &str = r#"{
    "id": "6f1a9d5e-2b7c-4e1f-9a3d-8c5b0e7f2a41",
    "kind": "order.created",
    "schema_version": 1,
    "occurred_at": "2026-08-14T10:15:00Z",
    "trace": { "traceparent": "00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01" },
    "data": { "order_id": "11111111-2222-3333-4444-555555555555", "item": "widget", "quantity": 4 }
}"#;

// ---------------------------------------------------------------------------
// Consumer side — what this service reads out of the outbox
// ---------------------------------------------------------------------------

#[test]
fn a_stored_outbox_row_is_accepted() {
    // `from_value` rather than `from_str`, because sqlx hands the JSONB column
    // over as a `serde_json::Value` - the same conversion the real relay does.
    let stored: serde_json::Value = serde_json::from_str(STORED_ROW).expect("fixture parses");

    let envelope: Envelope<OrderCommand> =
        serde_json::from_value(stored).expect("the gateway's stored shape must deserialise");

    assert_eq!(envelope.data.quantity, 4);
    assert!(envelope.is_supported());
}

#[test]
fn unknown_fields_in_a_stored_row_are_tolerated() {
    // Rows written by a newer gateway sit in the same table as older ones,
    // and this service may be the older half of the deploy.
    let from_the_future = r#"{
        "id": "6f1a9d5e-2b7c-4e1f-9a3d-8c5b0e7f2a41",
        "kind": "order.created",
        "schema_version": 1,
        "occurred_at": "2026-08-14T10:15:00Z",
        "data": {
            "order_id": "11111111-2222-3333-4444-555555555555",
            "item": "widget",
            "quantity": 4,
            "gift_wrap": true
        },
        "tenant": "acme"
    }"#;

    let envelope: Envelope<OrderCommand> = serde_json::from_str(from_the_future)
        .expect("a row from a newer gateway must still be relayable");

    assert_eq!(envelope.data.item, "widget");
}

// ---------------------------------------------------------------------------
// Provider side — what this service republishes
// ---------------------------------------------------------------------------

/// The relay must not alter the message it forwards.
///
/// Every field is compared, not just the payload. `id` and `occurred_at` are
/// the ones most likely to be "helpfully" regenerated by a future change, and
/// both would break consumer idempotency if they were.
#[test]
fn republishing_changes_nothing_about_the_message() {
    let stored: serde_json::Value = serde_json::from_str(STORED_ROW).expect("fixture parses");

    let read_back: Envelope<OrderCommand> =
        serde_json::from_value(stored.clone()).expect("must deserialise");

    // What the relay hands to `Messaging::publish`.
    let republished = serde_json::to_value(&read_back).expect("must serialise");

    let original: Envelope<OrderCommand> =
        serde_json::from_value(stored).expect("must deserialise");
    let forwarded: Envelope<OrderCommand> =
        serde_json::from_value(republished).expect("must deserialise");

    assert_eq!(
        original, forwarded,
        "the relay is a conduit; altering the message would break dedupe downstream"
    );
    assert_eq!(original.id, forwarded.id, "the message id must survive");
    assert_eq!(
        original.occurred_at, forwarded.occurred_at,
        "occurred_at describes the business event, not the relay's clock"
    );
}

/// The trace context stored with the row survives the hop.
///
/// This is the whole reason trace context lives in the envelope rather than
/// only in broker headers: the row sat in Postgres, and the relay restores the
/// originating context when it publishes. Losing it here would break the trace
/// at exactly the point the outbox makes the message durable.
#[test]
fn the_stored_trace_context_survives_republication() {
    let read_back: Envelope<OrderCommand> =
        serde_json::from_str(STORED_ROW).expect("must deserialise");

    assert!(
        read_back.trace.contains_key("traceparent"),
        "the relay needs this to rejoin the trace the request started"
    );

    let forwarded: Envelope<OrderCommand> =
        serde_json::from_value(serde_json::to_value(&read_back).expect("serialises"))
            .expect("deserialises");

    assert_eq!(forwarded.trace, read_back.trace);
}

/// The subject published to is the one the worker consumes from.
#[test]
fn the_published_subject_matches_the_shared_constant() {
    assert_eq!(subjects::ORDER_COMMAND_CREATED, "orders.command.created");
    assert_eq!(subjects::STREAM_COMMANDS, "ORDER_COMMANDS");
}

/// A row that cannot be decoded must fail loudly rather than publish garbage.
///
/// The relay marks a row published only after the broker acknowledges it, so
/// an undecodable row should stop that row rather than silently skip it.
#[test]
fn an_undecodable_row_is_an_error_not_a_silent_skip() {
    let corrupt = serde_json::json!({ "id": "not-a-uuid", "kind": "order.created" });

    assert!(
        serde_json::from_value::<Envelope<OrderCommand>>(corrupt).is_err(),
        "a malformed row must surface, not be quietly dropped"
    );
}

/// A brand-new envelope is not equal to a stored one.
///
/// Guards the mistake this service must never make: constructing a fresh
/// `Envelope` instead of forwarding the stored one, which would give every
/// relayed message a new id and defeat consumer dedupe.
#[test]
fn a_freshly_built_envelope_is_not_a_substitute_for_the_stored_one() {
    let stored: Envelope<OrderCommand> =
        serde_json::from_str(STORED_ROW).expect("must deserialise");

    let rebuilt = Envelope::new(
        "order.created",
        OrderCommand {
            order_id: Uuid::parse_str("11111111-2222-3333-4444-555555555555").expect("valid"),
            item: "widget".to_owned(),
            quantity: 4,
        },
    );

    assert_ne!(
        stored.id, rebuilt.id,
        "rebuilding would mint a new id and break at-least-once dedupe"
    );
}
